### ISSUE TITLE
Introspection tool

### ISSUE THREAD

**Issue by GaryHudmanAZGS** [ngds/ngds-metadatabase-v4#10]
With the catalog libraries, most direct data links can be found with static mapping of catalog links to download links specific to the libraries. Building a tool to allow users to manage direct link mapping can provide the majority of the introspection.

**Comment by GaryHudmanAZGS** [comment]
In progress -  link mapping data structure is available, built in hooks to the data quality check service.  Missing the UI to catalog mapping and version control..

**Comment by aazaff** [comment]
Can you update and close this issue with the relevant commits?

**Comment by aazaff** [comment]
I don't know which commit this was related to, but this is finished.
