### ISSUE TITLE
Data Rescue all Data Exchange Model templates

### ISSUE THREAD

**Issue by aazaff** [ngds/ngds-metadatabase-v4#14]
@smrgeoinfo, looking at the list of data exchange models on the NGDS home page (http://geothermaldata.org/content-models/data-interchange-content-models), many of them have dead links within them and it is not possible to download the example template. The majority of those links seem to be to schemas.usgin.org (e.g., http://schemas.usgin.org/files/well-log-observation/0.8/WellLog.xls).

I'm not sure what server schemas.usgin.org runs off of or if it is even still run by AZGS? Luckily these schemas all seem to be backed up on GitHub (https://github.com/usgin-models), but I cannot see who is the owner of that org.

I'd like to edit all of the entries on the NGDS information page to the respective GitHub repositories and just drop the schemas.usgin.org links entirely. However, if there is some reason that we should still be using schemas.usgin.org as our primary distribution point (please let me know) and we can figure out how to get it running again.

**Comment by aazaff** [comment]
@Lbookman Please go through and update these links to be to the GitHub instead of schemas.usgin.org

**Comment by smrgeoinfo** [comment]
Linking to models in github makes sense.
schemas.usgin.org had functions to provide validation services for csv files.  I can't recall at this point where it was deployed, but suspect it was on one of the AZGS servers.   Maybe Gary remembers.

**Comment by aazaff** [comment]
Excellent! Gary thinks that the schemas.usgin.org server is under AZGS/USGIN accounts on AWS. We should set time to investigate its status further and see if there's anything AZGS and/or USGIN wants to salvage from it. I don't like paying for an unnecessary AWS server. I'll open a separate issue.

**Comment by Lbookman** [comment]
changed links to github
