### ISSUE TITLE
Do not have the search results as a separate internal frame.

### ISSUE THREAD

**Issue by aazaff** [ngds/ngds-metadatabase-v4#2]
![search_frame](https://user-images.githubusercontent.com/10422595/84301125-2a8a0d80-ab08-11ea-95bf-46d7ef2e6389.PNG)

The search results currently seem to be returned in an iframe that needs to be scrolled through to view all of your hits. It should not be scrollable, but should be static and fill up the page. There is plenty of room on the page for this, particularly since the facets on the left extend well below the bottom of the search-results iframe.

Also, as indicated in this picture, there may be some unintended rendering problems with the frame approach.

This was the most prominent of @hsnellen and @Lbookman's feedback.

**Comment by aazaff** [comment]
I recognize it is not an actual iframe. Here is the offending section. I'm not good at CSS so I don't know the best fix.

![offending_section](https://user-images.githubusercontent.com/10422595/84303150-59ee4980-ab0b-11ea-8cf1-654a4f59b921.PNG)

**Comment by GaryHudmanAZGS** [comment]
Fixed
