### ISSUE TITLE
Search by data Tier (i.e., add a Tier facet)

### ISSUE THREAD

**Issue by aazaff** [ngds/ngds-metadatabase-v4#25]
The original NGDS formulation sorted datatypes into Tier I, Tier II, and Tier III. Yet there has never been a working way (for at least long as I have been here) and I would really like to see this added as a searchable parameter.

**Comment by smrgeoinfo** [comment]
Good question, and to answer fully I'd have to be able to look at some of the ISO metadata that has more information in it (where is is now?).  Have a look at https://github.com/ngds/ckanext-ngds-bku03232018/issues/401; I think the tier 3 data were indicated by keywords with usgincm prefix or theme.  
If I were going to update the system, I'd move toward csv/web formats for delivery and use schema.org metadata embedded in landing pages following what we've been doing in EarthCube (see https://github.com/ESIPFed/science-on-schema.org/blob/master/guides/Dataset.md and discussions in https://github.com/ESIPFed/science-on-schema.org/issues.   The tier III data would have distributions using formats registered in the resource registry, identified by URI in distribution format. Tier 1 and 2 would likewise have registered formats at a  more generic level (text, doc, pdf, xls mime types).   One of those maintenance/update things that would be good to do to keep NGDS alive....

**Comment by GaryHudmanAZGS** [comment]
Correct search syntax error, it was failing on special case handling for ":" now when the "usgincm key work is entered, the tier 3 records are found.
