### ISSUE TITLE
Turn the data-type buttons on search-results into static labels.

### ISSUE THREAD

**Issue by aazaff** [ngds/ngds-metadatabase-v4#4]
![buttons](https://user-images.githubusercontent.com/10422595/84302099-ac2e6b00-ab09-11ea-91e2-d5d538c37200.PNG)

I have a few problems with these buttons on the search-results.

1. I think it is redundant to have both the file/name link and the button be interactive. Really only one needs to be clickable. 
2. If there are multiple data products in a record, then there is no name or description (because there's no room), but that means you have no idea where the buttons lead. For example, some items say LINK LINK LINK. I have no idea where those buttons will take me.

I think what might be best is to turn these into just labels so you can quickly see at a glance that data of a certain type is in a record, but don't make them actual buttons to take you anywhere. Make it so that you still have to click on/open the record to go to the data.

**Comment by GaryHudmanAZGS** [comment]
Done, uses a dropdown ...

**Comment by aazaff** [comment]
We decided to revert this back to the way it was originally.
