### ISSUE TITLE
Move the pagination buttons to the bottom of the rec-results

### ISSUE THREAD

**Issue by aazaff** [ngds/ngds-metadatabase-v4#5]
@Lbookman wants the buttons for scrolling to the next page of the search results to be at the bottom of the results rather than at the top. I am indifferent.

She does want to keep the report of how many hits etc. at the top.

**Comment by GaryHudmanAZGS** [comment]
The length of the page is variable (especially since its taken out of its own scrollable block), so it will be cumbersome to scroll to bottom to find page buttons.

**Comment by aazaff** [comment]
We decided to put the pagination buttons at both the top and bottom.

**Comment by aazaff** [comment]
Was this ever implemented? Can you log the commit and close this issue? @GaryHudmanAZGS

**Comment by aazaff** [comment]
I should also note there is no pagination information in the /ingestion endpoint. You have to manually guess the offset.

**Comment by aazaff** [comment]
This issue is no longer relevant.
