### ISSUE TITLE
Recommended changes to the map search tool.

### ISSUE THREAD

**Issue by aazaff** [ngds/ngds-metadatabase-v4#7]
![Capture2](https://user-images.githubusercontent.com/10422595/84304681-ba7e8600-ab0d-11ea-9d5e-2b7c942bd243.PNG)

1. @Lbookman does not like that the autocomplete window blocks the map. I personally don't think this is avoidable or a big deal. But I wanted to record her feedback on it.

2. We all agree that the eyeglass icon for the bbox button is really confusing, but I don't know what a better icon would be. Maybe you could talk to Laura about ideas.

3. We all agreed that it would be better for the bbox button to be inside the map rather than on the top or the bottom, but if you cannot put it inside of the map, Laura would prefer for it to be on top.

**Comment by GaryHudmanAZGS** [comment]
Before changing the button, I used the new geoportal as a template,  so maybe if we look at it first, it might spur some ideas 
http://datadiscoverystudio.org/geoportal/#searchPanel

**Comment by aazaff** [comment]
I like that the data discovery buttons are very explicit (with text) about what they do. Still seems strange they won't allow you to just "draw" a bbox. We can discuss this at the 7/2/20 meeting.

**Comment by aazaff** [comment]
I think we have determined that it is fine with the new changes.

**Comment by aazaff** [comment]
Improvements to the MAP interface are a long-term (but very important) issue for NGDS, hence I've attached them to the longterm NGDS milestone.

I would like for us to consult with @kiricarini and @hsnellen to solicit more feedback on improvements we can do for the map search tool.

**Comment by smrgeoinfo** [comment]
I'd suggest removing the 'Map' button on the home page until the map interface is functional in some way.
