### ISSUE TITLE
Introspection - ingestion tool

### ISSUE THREAD

**Issue by GaryHudmanAZGS** [ngds/ngds-metadatabase-v4#9]
Basic api is working - requires testing,  there are two outstanding issues the url for the metadata record is incorrect, and the url status is incorrect.

**Comment by GaryHudmanAZGS** [comment]
Fixed - metadata record url has been corrected

**Comment by GaryHudmanAZGS** [comment]
Url status for ingestion api is working - first level check.  Added server side data quality check tool that saves results to db..  Deep inspection tool in development.

**Comment by aazaff** [comment]
I'm assuming this supersedes or is related to #10? Can you update both/either with the relevant commits and close?
